pipeline {
  agent { label 'agent' }
  tools {
    maven 'maven'
  }
  stages {
    stage('Build') {
      steps {
        sh 'mvn clean package'
        }
        post {
          success {
            archiveArtifacts artifacts: '*.jar', fingerprint: true
            }
          }
      }
    }
}